// <auto-generated />
namespace Shop.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _12285 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_12285));
        
        string IMigrationMetadata.Id
        {
            get { return "202112280805085_1228-5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
