// <auto-generated />
namespace Shop.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _12289 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_12289));
        
        string IMigrationMetadata.Id
        {
            get { return "202112280950351_1228-9"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
